formatting

diff --git a/bin/final-plot-management/plot/Excavator b/bin/final-plot-management/plot/Excavator
--- a/bin/final-plot-management/plot/Excavator
+++ b/bin/final-plot-management/plot/Excavator
@@ -3,22 +3,22 @@
 ## Description: Excavator - This script is not to be ran directly, and is called by 'Foreman'. This script analyzes the chia plot directories, and determines the best drive to move the plot to from the -d buffer drive.
 
 CheckDeps() {
-	if ! command -v ProofOfSpace &> /dev/null; then
-		echo "ERROR: Missing ProofOfSpace"
-		echo "Get it - https://github.com/Chia-Network/chiapos"
-		exit 1
-	fi
+    if ! command -v ProofOfSpace &> /dev/null; then
+        echo "ERROR: Missing ProofOfSpace"
+        echo "Get it - https://github.com/Chia-Network/chiapos"
+        exit 1
+    fi
 }
 
 CHIA_PATH=$HOME/chia-blockchain
 # Example: CHIA_PATH=$HOME/chia-blockchain
 
 CheckPath() {
-	if [[ -z $CHIA_PATH ]]; then
-  	  echo "ERROR: CHIA_PATH is unset."
-    	echo "Edit $0, and set the value of line #4 to the path of your chia-blockchain repo."
-    	exit 1
-	fi
+    if [[ -z $CHIA_PATH ]]; then
+        echo "ERROR: CHIA_PATH is unset."
+        echo "Edit $0, and set the value of line #4 to the path of your chia-blockchain repo."
+        exit 1
+    fi
 }
 
 # This is configured to work with the particular setup of my system.
@@ -40,99 +40,97 @@ CheckPath() {
 
 PLOTARG=$1
 CheckInteractive() {
-	if [[ -z $WENDY_INODE ]]; then
-  	if [[ -z $PLOTARG ]]; then
-    	echo "To run this manually, execute as:"
-     	echo "replot <NFT_PLOT>"
-     	exit 1
-   	else
-    	WENDY_INODE=$(realpath "$PLOTARG")
+    if [[ -z $WENDY_INODE ]]; then
+        if [[ -z $PLOTARG ]]; then
+            echo "To run this manually, execute as:"
+            echo "replot <NFT_PLOT>"
+            exit 1
+        else
+            WENDY_INODE=$(realpath "$PLOTARG")
+        fi
     fi
-	fi
 }
 
 MOUNT_LIST="/tmp/$(basename "$0")-mounts.$$.list"
 FindMounts() {
-	echo "Finding plot locations..."
-	"$CHIA_PATH"/venv/bin/chia plots show | \
-		grep 'solo\|pool' | \
-		sed 's,/*[^/]\+/*$,,' | \
-		sort -R >"$MOUNT_LIST"
+    echo "Finding plot locations..."
+    "$CHIA_PATH"/venv/bin/chia plots show | \
+        grep 'solo\|pool' | \
+        sed 's,/*[^/]\+/*$,,' | \
+        sort -R >"$MOUNT_LIST"
 }
 
 FindDupes() {
-	echo "Finding presence of existing plots..."
-	PLOTNAME=$(basename "$WENDY_INODE")
-	PLOTDUPE=$(find /mnt/plots*/ -type f -name '*'$PLOTNAME'*')
-	DUPEPATH=$(dirname "$PLOTDUPE")
- 	if find /mnt/plots*/ -type f -name '*'$PLOTNAME'*' | grep -q .; then
-		if "$(ProofOfSpace check -f "$PLOTDUPE" 1 &>/dev/null)"; then
-			echo "Plot $PLOTNAME already exists at $DUPEPATH, and is valid"
-			echo "Consider deleting $WENDY_INODE"
-			exit 1
-		else
-			echo "Plot $PLOTNAME already exists at $DUPEPATH, but does not appear to be valid"
-			echo "Plot transfer may already be in progress, or incomplete plot may need to be removed"
-			exit 1
-		fi
-	fi
+    echo "Finding presence of existing plots..."
+    PLOTNAME=$(basename "$WENDY_INODE")
+    PLOTDUPE=$(find /mnt/plots*/ -type f -name '*'$PLOTNAME'*')
+    DUPEPATH=$(dirname "$PLOTDUPE")
+    if find /mnt/plots*/ -type f -name '*'$PLOTNAME'*' | grep -q .; then
+        if "$(ProofOfSpace check -f "$PLOTDUPE" 1 &>/dev/null)"; then
+            echo "Plot $PLOTNAME already exists at $DUPEPATH, and is valid"
+            echo "Consider deleting $WENDY_INODE"
+            exit 1
+        else
+            echo "Plot $PLOTNAME already exists at $DUPEPATH, but does not appear to be valid"
+            echo "Plot transfer may already be in progress, or incomplete plot may need to be removed"
+            exit 1
+        fi
+    fi
 }
 
 FindBusy() {
-	echo "Finding busy volumes..."
-	BUSY_LIST="/tmp/$(basename "$0")-busy.$$.list"
-	pgrep -fa "^rsync" | \
-		grep 'plot' | \
-		grep 'pool/\|solo/' | \
-		sed -e 's/^.* //;s/.$//' | \
-		sort | \
-		uniq > "$BUSY_LIST"
+    echo "Finding busy volumes..."
+    BUSY_LIST="/tmp/$(basename "$0")-busy.$$.list"
+    pgrep -fa "^rsync" | \
+        grep 'plot' | \
+        grep 'pool/\|solo/' | \
+        sed -e 's/^.* //;s/.$//' | \
+        sort | \
+        uniq > "$BUSY_LIST"
 }
 
 RemoveBusy() {
-	echo "Excluding busy volumes..."
-	if [[ -s "$BUSY_LIST" ]]; then
-		while read -r BUSY; do
-    	ESC_BUSY="$(dirname $(printf '%s\n' "$BUSY") | sed -e 's/[\/&]/\\&/g')"
-    	sed -i "/^$ESC_BUSY\b/Id" "$MOUNT_LIST"
-		done <"$BUSY_LIST"
-	fi
+    echo "Excluding busy volumes..."
+    if [[ -s "$BUSY_LIST" ]]; then
+        while read -r BUSY; do
+        ESC_BUSY="$(dirname $(printf '%s\n' "$BUSY") | sed -e 's/[\/&]/\\&/g')"
+        sed -i "/^$ESC_BUSY\b/Id" "$MOUNT_LIST"
+        done <"$BUSY_LIST"
+    fi
 }
 
 CheckMounts() {
-	n=0
-	until [ "$n" -ge 5 ]; do
-		FindBusy
-		RemoveBusy
-		[ -s "$MOUNT_LIST" ] && break
-		n=$((n+1))
-		echo "No available mounts. Checking again in 5 minutes..."
-		sleep 5m
-	done
-	if [[ $n -eq 6 ]]; then
-		echo "Could not find an available mount. Giving up"
-		exit 1
-	fi
+    n=0
+    until [ "$n" -ge 5 ]; do
+        FindBusy
+        RemoveBusy
+        [ -s "$MOUNT_LIST" ] && break
+        n=$((n+1))
+        echo "No available mounts. Checking again in 5 minutes..."
+        sleep 5m
+    done
+    if [[ $n -eq 6 ]]; then
+        echo "Could not find an available mount. Giving up"
+        exit 1
+    fi
 }
 
 IterateMounts() {
-	while read -r TARGET; do
-		PLOTNAME=$(basename "$WENDY_INODE")
-		PLOTSIZE=$(stat --printf='%s' "$WENDY_INODE")
-		AVAIL=$(df --output=avail --block-size=1 "$TARGET" | tail -n 1 | xargs)
-		PLOTCOUNT="$(("$AVAIL" / "$PLOTSIZE"))"
-		echo "Evaluating mount..."
-		if [[ $PLOTCOUNT -gt 0 ]]; then
-			echo "Moving $WENDY_INODE to $TARGET/pool/..."
-			rsync -a --remove-source-files "$WENDY_INODE" "$TARGET"/pool/
-			if [[ -f "$TARGET"/pool/"$PLOTNAME" ]]; then
-				echo "$PLOTNAME has been moved to $TARGET/pool/, and is ready for farming!"
-				rm "$BUSY_LIST"
-				rm "$MOUNT_LIST"
-			fi
-		break
-		fi
-	done < "$MOUNT_LIST"
+    while read -r TARGET; do
+        PLOTNAME=$(basename "$WENDY_INODE")
+        PLOTSIZE=$(stat --printf='%s' "$WENDY_INODE")
+        AVAIL=$(df --output=avail --block-size=1 "$TARGET" | tail -n 1 | xargs)
+        PLOTCOUNT="$(("$AVAIL" / "$PLOTSIZE"))"
+        echo "Evaluating mount..."
+        if [[ $PLOTCOUNT -gt 0 ]]; then
+            echo "Moving $WENDY_INODE to $TARGET/pool/..."
+            rsync -a --remove-source-files "$WENDY_INODE" "$TARGET"/pool/
+            if [[ -f "$TARGET"/pool/"$PLOTNAME" ]]; then
+                echo "$PLOTNAME has been moved to $TARGET/pool/, and is ready for farming!"
+            fi
+            break
+        fi
+    done < "$MOUNT_LIST"
 }
 
 CheckDeps
@@ -142,3 +140,6 @@ FindMounts
 FindDupes
 CheckMounts
 IterateMounts
+
+rm "$MOUNT_LIST"
+rm "$BUSY_LIST"
